[workspace]
channels = ["conda-forge"]
name = "competition-news-feed"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.14.*"
rich = ">=15.0.0,<16"
streamlit = ">=1.63.0,<2"
pandas = ">=3.0.5,<4"

[pypi-dependencies]
tavily-python = ">=0.8.2, <0.9"

[activation]
scripts = ["load_env.sh"]
